### ISSUE TITLE
Remove the HSQLDB ssclj DB from dependency and autostart

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServerDeps#47]
It should be done  [here](https://github.com/slipstream/SlipStreamServerDeps/blob/master/hsqldb/rpm/src/data/server.properties#L3), [here](https://github.com/slipstream/SlipStreamServerDeps/blob/master/hsqldb/rpm/src/etc/hsqldb.cfg#L6) and [here](https://github.com/slipstream/SlipStreamServerDeps/blob/master/hsqldb/rpm/src/etc/hsqldb.service#L4)

**Comment by loomis** [comment]
Note that the ssclj server still has a dependency on the 'slipstream' database in hsqldb, so the service dependency should not yet be removed.  (This dependency is so the external authentication can create users when needed.) 

The ssclj database in hsqldb has been removed from the configuration.
