### ISSUE TITLE
Elasticsearch backup fails with "[es_backup] missing"

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServerDeps#56]
It looks like it fails since the end of Sept'16

```
Wed Sep 28 16:30:01 UTC 2016
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   179  100   179    0     0   5659      0 --:--:-- --:--:-- --:--:--  5774
{"error":{"root_cause":[{"type":"repository_missing_exception","reason":"[es_backup] missing"}],"type":"repository_missing_exception","reason":"[es_backup] missing"},"status":404}
```

**Comment by loomis** [comment]
Documentation for backing up ES is available for [v2](https://www.elastic.co/guide/en/elasticsearch/guide/current/backing-up-your-cluster.html) and for [v5](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html).

Note that there is also an official plugin that permits backing up directly to an S3 bucket.
