### ISSUE TITLE
nagios backup probe should only check backups

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServerDeps#6]
The current nagios backup probe actually does the full backup.  This causes a problem because the backup and probe take longer than 60 seconds to complete now.  Although the timeout can be extended in the definition of the probe, it cannot exceed the maximum timeout given in the NRPE configuration file on the client.  The default for this parameter is 60 seconds.  In any case, it is not a good idea to do significant calculations in a probe.

The implementation should be refactored such that a cron job executes the backup and the nagios probe only verifies that the backup has been done recently.

**Comment by schaubl** [comment]
This is done.
